# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='normalized_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='skill_normalized_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rankingresults',
            name='average_score',
            field=models.FloatField(default=0),
        ),
    ]
