# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(default='', max_length=255),
        ),
    ]
