# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160727_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileskill',
            old_name='skill_normalized_score',
            new_name='normalized_skill_score',
        ),
        migrations.AddField(
            model_name='skill',
            name='average_score',
            field=models.FloatField(default=0),
        ),
    ]
