# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160721_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='github_fork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='github_forks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='main.Skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='homepage',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
