# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160723_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RankingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='overall_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='max_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Skill'),
        ),
    ]
